### PR TITLE
Add hook for subclass to handle enriching

### PR DESCRIPTION
**Pull request by aarcro**
With this change it is trivial to subclass Enrich and provide an implementation of `enrich_instance` which might serialize the instance so the final results can be dropped into a `rest_framework.Response`.

### CODE REVIEW

**Comment by aarcro** [comment]
Example subclass that takes a map of model classes to serializer classes

```python
from stream_django.enrich import Enrich

class EnrichWithSerializers(Enrich):
    def __init__(self, *args, **kwargs):
        # serializers kwarg should be a mapping of classes (probably models)
        # to serialzer classes
        self.serializers = kwargs.pop('serializers', {})
        self.context = kwargs.pop('serializer_context', {})

        super().__init__(*args, **kwargs)

    def enrich_instance(self, instance):
        Serializer = self.serializers.get(instance.__class__, None)

        if Serializer is None:
            # No change made to instances with no serializer
            return instance

        return Serializer(instance, context=self.context).data
```

**Comment by dwightgunning** [comment]
Thanks for the PR @aarco - I'll review this.

**Comment by dwightgunning** [comment]
@aarcro - looping back to this now. Appreciate you providing a use-case for the change.

I'm just thinking that it is really about the serialisation, rather than enrichment, and this should logically occur after passing the activities through the Enrich functions. Would you agree?

Let me know if there an aspect or detail I'm overlooking but I think for now we'd prefer to skip this change.

**Comment by aarcro** [comment]
It's really nice because it saves having to iterate back through the activity structure to find the models to serialize. The only thing I'm going to do with a response from Stream is return the contents with Django Rest Framework, I'd think that's a fairly common pattern.

**Comment by dwightgunning** [comment]
I can understand the interest in avoiding the repetitive looping. I recall the DRF serializers and Django serializers have different interfaces.

I'm going to look at throwing a demo app together with DRF to take a look at how this works end to end. That should give us a better feel for the right approach. If you have a public project based on a stream-django fork with your PR in place I'd be happy to take a look at that.

**Comment by aarcro** [comment]
Unfortunately I don't have a public project using this right now.

**Comment by colonelrascals** [comment]
Where are we on this? Looking to integrate Stream with DRF

**Comment by JJZolper** [comment]
@dwightgunning were you able to put an example together of the new additions for serialization with stream and drf?

**Pull request merged**
